allowBuilds:
  esbuild: false
  unrs-resolver: false

ignoredBuiltDependencies:
  - rollup
  - unrs-resolver

minimumReleaseAgeExclude:
  - comment-parser@1.4.7 || 1.4.8
  - '@es-joy/jsdoccomment@0.89.0 || 0.90.0 || 0.93.2'
  - eslint-plugin-jsdoc@63.2.1 || 63.2.2 || 63.3.1 || 64.0.2
  - jsdoc-type-pratt-parser@7.3.0 || 8.0.0 || 9.0.0 || 9.0.1 || 9.1.0 || 9.1.1 || 9.1.2 || 9.2.0
  - eslint-config-ash-nazg@40.2.0 || 41.1.0 || 41.1.1 || 42.1.1 || 42.2.0
  - eslint-plugin-mocha@12.0.0
  - eslint@10.8.1
  - '@typescript-eslint/eslint-plugin@8.67.0'
  - '@typescript-eslint/parser@8.67.0'
  - '@typescript-eslint/project-service@8.67.0'
  - '@typescript-eslint/scope-manager@8.67.0'
  - '@typescript-eslint/tsconfig-utils@8.67.0'
  - '@typescript-eslint/type-utils@8.67.0'
  - '@typescript-eslint/types@8.67.0'
  - '@typescript-eslint/typescript-estree@8.67.0'
  - '@typescript-eslint/utils@8.67.0'
  - '@typescript-eslint/visitor-keys@8.67.0'
  - typescript-eslint@8.67.0

onlyBuiltDependencies:
  - esbuild
  - rollup
